[package]
name = "ezcfg_config"
version = "0.1.0"
edition = "2021"

[dependencies]
ezcfg_cli = { path = "../cli" }
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
assert_fs = "1.1"
