[package]
name = "ezcfg_linker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ezcfg_cli = { path = "../cli" }
num_cpus = "1.16"
indicatif = "0.17"
